export default [
  {
    id: 1,
    postedOn: "2024-06-25",
    title: "ios Developer",
    company: "Apple",
    location: "Remote",
    type: "Full-time",
    experience: "Mid Level",
    skills: ["SwiftUI", "UiKit", "Core Data"],
    job_link:
      "https://in.best-jobs-online.com/serp/2/?position=Apple&locphysical=150034&qrn_source=bing&qrn_medium=cpc&qrn_campaign=439154329&msclkid=10e7d43068d414fbaa6fb2a146abb823&utm_source=bing&utm_medium=cpc&utm_campaign=IN%7CPositionKWs&utm_term=Apple%20careers&utm_content=Apple",
  },
  {
    id: 2,
    postedOn: "2024-07-10",
    title: "Frontend Developer",
    company: "odoo",
    location: "In-office",
    type: "Part-time",
    experience: "Junior Level",
    skills: ["Javascript", "Html", "TailWindCSS"],
    job_link: "https://www.odoo.com/jobs",
  },
  {
    id: 3,
    postedOn: "2024-07-05",
    title: "Frontend Developer",
    company: "Felix It's",
    location: "In-office",
    experience: "Junior Level",
    type: "Part-time",
    skills: ["Javascript", "ReactJs", "NextJs", "Bootstrap"],
    job_link: "https://www.felix-its.com/",
  },
  {
    id: 4,
    postedOn: "2024-06-10",
    title: "Backend Developer",
    company: "Flipkart",
    location: "Hybrid",
    type: "Contract",
    experience: "Senior Level",
    skills: ["Django", "python", "MySQL"],
    job_link:
      "https://www.flipkartcareers.com/?otracker=${otracker}_navlinks#!/",
  },
  {
    id: 5,
    postedOn: "2024-07-11",
    title: "Android Developer",
    company: "Amazon",
    location: "Remote",
    type: "Full-time",
    experience: "Fresher",
    skills: ["Java", "Database"],
    job_link: "https://amazon.jobs/en/",
  },
];
